#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


#  Source utility functions.
source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"


#  On slave/serving gears, need to do the install as part of deploy
#  so check if its needed. Just ensure the custom Node[.js] version is
#  installed.
ensure_node_is_installed

# Create meteor bundle
source "${OPENSHIFT_REPO_DIR}/.openshift/lib/setup_meteor_env"

if [ -d "${OPENSHIFT_REPO_DIR}/meteor/.meteor" ]; then

   echo Creating Meteor.js bundle...
   cd ${OPENSHIFT_REPO_DIR}/meteor
   meteor bundle bundle.tar.gz

   echo Deploying Meteor.js bundle to ${OPENSHIFT_REPO_DIR}...
   tar xzf bundle.tar.gz --strip-components=1 -C ../
   rm -f bundle.tar.gz
else
   echo
   echo "Meteor.js application not found."
   echo "Copy your code into meteor/ folder and push again."
   echo
fi
